# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: '#about'
    weight: 10
  - name: Research
    url: '#posts'
    weight: 20
 # - name: Talks
 #   url: '#skills'
 #   weight: 30
  - name: Teaching
    url: '#accomplishments'
    weight: 30
  - name: Contact
    url: '#contact'
    weight: 40
  - name: CV
    url: https://www.dropbox.com/scl/fi/tnlj61nbc4i0jiz5brrq4/CV.pdf?rlkey=90e0m88761jfdsncapzg6zlaz&dl=0
